title: Action

options:
  status: true
  sort: flip

fields:
  title:
    label: Title
    type: title

  intro_text:
    label: Main Text 
    type: textarea

  further_info:
    label: What You Can Do
    type: textarea
    help: this is displayed in the area below the 'What you can do' link

  description:
    label: Short Description 
    type: text

  status_message:
    label: Status Message
    type: text
    maxLength: 25

  action_type:
    label: Action Type
    type: select
    options: 
      electoral: Elections, Party Politics, Moving Left - Blue
      mindfulness: Mindfulness, Being The Change - Purple
      stops_and_checks: Stops and Checks - Pink
      two_hours: 2 HAW Specific - Grey
      anti_trump: Anti Trump - Orange ;-p
      personal: Personal Actions - Yellow
      policy: Policy Issues - Green
  
  cause_type: 
    label: Cause Type
    type: select
    options:
      healthcare: Healthcare 
      reproductive_rights: Reproductive Rights 
      environment: Environment 
      immigration: Immigration 
      civil_rights: Civil Rights 
      press_freedom: Press Freedom
      privacy: Privacy
      corruption: Corruption

  tags:
    label: Tags
    type: tags
    lower: true
    separator: ,

  is_active:
    type: checkbox
    label: active?
    text: Is this an active action?
    default: 1








